name: pretium_app
description: "Pretium App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.8.0
  lottie: ^3.1.3
  pinput: ^3.0.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0

  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    -  assets/icons/
    - assets/svgs/